import { useEffect, useMemo, useState } from "react";
import { useParams, useNavigate, useSearchParams } from "react-router-dom";
import toast from "react-hot-toast";
import { useAppContext } from "../context/AppContext";

export default function RoomDetails() {
  const { id } = useParams(); const [searchParams] = useSearchParams(); const { axios, authHeaders, currency, user } = useAppContext(); const navigate = useNavigate();
  const [room,setRoom]=useState(null),[inDate,setIn]=useState(() => searchParams.get("checkInDate") || ""),[outDate,setOut]=useState(() => searchParams.get("checkOutDate") || ""),[guests,setGuests]=useState(() => Math.max(1, Number(searchParams.get("guests")) || 1)),[available,setAvailable]=useState(null),[busy,setBusy]=useState(false),[booking,setBooking]=useState(false),[activeImage,setActiveImage]=useState(0);
  useEffect(()=>{let active=true;axios.get(`/api/rooms/${id}`).then(({data})=>{if(active&&data.success)setRoom(data.room)}).catch(e=>{if(active)toast.error(e.response?.data?.message||e.message)});return()=>{active=false}},[id]);
  useEffect(()=>setAvailable(null),[inDate,outDate,guests]);
  const nights=useMemo(()=>inDate&&outDate&&new Date(outDate)>new Date(inDate)?Math.round((new Date(outDate)-new Date(inDate))/86400000):0,[inDate,outDate]);
  const total=nights*Number(room?.pricePerNight||0);
  const check=async()=>{if(!inDate||!outDate||new Date(outDate)<=new Date(inDate))return toast.error("Choose valid dates");if(Number(guests)>room.maxGuests)return toast.error(`Maximum ${room.maxGuests} guests`);try{setBusy(true);const {data}=await axios.post("/api/bookings/check-availability",{room:id,checkInDate:inDate,checkOutDate:outDate,guests:Number(guests)});setAvailable(data.isAvailable);toast[data.isAvailable?"success":"error"](data.isAvailable?"Room is available":"Room is unavailable")}catch(e){toast.error(e.response?.data?.message||e.message)}finally{setBusy(false)}};
  const book=async()=>{if(!user)return toast.error("Please sign in first");if(available!==true)return check();try{setBooking(true);const {data}=await axios.post("/api/bookings",{room:id,checkInDate:inDate,checkOutDate:outDate,guests:Number(guests)},await authHeaders());if(data.success){toast.success("Booking created. Continue to payment from My Bookings.");navigate("/my-bookings")}}catch(e){toast.error(e.response?.data?.message||e.message);setAvailable(null)}finally{setBooking(false)}};
  if(!room)return <main className="mx-auto max-w-6xl px-4 py-20 text-center text-gray-500">Loading room...</main>;
  const images=room.images||[]; const today=new Date().toISOString().slice(0,10);
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><button onClick={()=>navigate(-1)} className="text-sm font-medium text-gray-500 hover:text-primary">← Back</button>
    <div className="mt-5 grid gap-3 lg:grid-cols-[1.5fr_1fr]"><div className="overflow-hidden rounded-3xl bg-gray-100"><div className="h-72 sm:h-[420px]"><img src={images[activeImage]} alt={room.roomType} className="h-full w-full object-cover"/></div>{images.length>1&&<div className="flex gap-2 overflow-x-auto bg-white p-3">{images.map((img,i)=><button key={img+i} onClick={()=>setActiveImage(i)} className={`h-16 w-20 shrink-0 overflow-hidden rounded-lg border-2 ${activeImage===i?"border-primary":"border-transparent"}`}><img src={img} alt="" className="h-full w-full object-cover"/></button>)}</div>}</div><div className="flex flex-col justify-end rounded-3xl bg-gray-50 p-7"><p className="text-sm font-semibold text-primary">{room.hotel?.city}</p><h1 className="mt-2 text-3xl font-bold">{room.hotel?.name}</h1><h2 className="mt-2 text-xl text-gray-600">{room.roomType}</h2><p className="mt-2 text-sm text-gray-500">{room.hotel?.address}</p><div className="mt-6 flex flex-wrap gap-2">{(room.amenities||[]).map(a=><span key={a} className="rounded-full bg-white px-3 py-1.5 text-sm text-gray-600 shadow-sm">{a}</span>)}</div></div></div>
    <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_380px]"><section><h2 className="text-2xl font-bold">Room details</h2><p className="mt-4 leading-7 text-gray-600">Enjoy a comfortable stay in this {room.roomType.toLowerCase()} with space for up to {room.maxGuests} guest{room.maxGuests!==1?"s":""}.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border p-5"><p className="text-xs text-gray-500">Guest capacity</p><p className="mt-1 font-semibold">Up to {room.maxGuests} guests</p></div><div className="rounded-2xl border p-5"><p className="text-xs text-gray-500">Nightly rate</p><p className="mt-1 font-semibold">{currency}{room.pricePerNight}</p></div></div></section>
      <aside className="h-fit rounded-3xl border border-gray-100 bg-white p-6 shadow-lg lg:sticky lg:top-24"><div className="flex items-end justify-between"><div><span className="text-3xl font-bold">{currency}{room.pricePerNight}</span><span className="ml-1 text-sm text-gray-500">/ night</span></div></div><div className="mt-6 grid gap-4"><label className="text-sm font-semibold text-gray-700">Check-in<input type="date" min={today} value={inDate} onChange={e=>setIn(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-semibold text-gray-700">Check-out<input type="date" min={inDate||today} value={outDate} onChange={e=>setOut(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-semibold text-gray-700">Guests<input type="number" min="1" max={room.maxGuests} value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)))} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label></div>{nights>0&&<div className="mt-6 space-y-2 border-t pt-4 text-sm"><div className="flex justify-between text-gray-500"><span>{currency}{room.pricePerNight} × {nights} night{nights!==1?"s":""}</span><strong className="text-gray-900">{currency}{total}</strong></div><div className="flex justify-between border-t pt-3 font-bold"><span>Total</span><span>{currency}{total}</span></div></div>}{available!==null&&<p className={`mt-4 rounded-xl p-3 text-sm font-medium ${available?"bg-green-50 text-green-700":"bg-red-50 text-red-700"}`}>{available?"✓ Dates are available.":"These dates are unavailable."}</p>}<button onClick={available===true?book:check} disabled={busy||booking} className="mt-5 w-full rounded-xl bg-primary px-5 py-3.5 font-semibold text-white transition hover:bg-blue-700 disabled:opacity-60">{busy?"Checking availability...":booking?"Creating booking...":available===true?"Book this room":"Check availability"}</button><p className="mt-3 text-center text-xs text-gray-500">Final availability and price are verified securely on the server.</p></aside>
    </div></main>;
}
